version: "3.8"

services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:latest
    container_name: "postgresql_service"
    restart: always
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  # Servicio de pgAdmin
  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: "pgadmin_service"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
